#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Mar 18 06:29:31 UTC 2026
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_hamming_logic_encoder_behav -key {Behavioral:sim_1:Functional:tb_hamming_logic_encoder} -tclbatch tb_hamming_logic_encoder.tcl -view /home/minami/Coding_IPDesign/IP_lecture/hamming_logic/hamming_logic_proj/tb_hamming_logic_encoder_behav.wcfg -log simulate.log"
xsim tb_hamming_logic_encoder_behav -key {Behavioral:sim_1:Functional:tb_hamming_logic_encoder} -tclbatch tb_hamming_logic_encoder.tcl -view /home/minami/Coding_IPDesign/IP_lecture/hamming_logic/hamming_logic_proj/tb_hamming_logic_encoder_behav.wcfg -log simulate.log

